{% set version = "2.1.2" %}

package:
  name: android-libjpeg
  version: {{ version }}

source:
  url: https://github.com/libjpeg-turbo/libjpeg-turbo/archive/refs/tags/{{ version }}.tar.gz
  sha256: e7fdc8a255c45bc8fbd9aa11c1a49c23092fcd7379296aeaeb14d3343a3d1bed

build:
  number: 1
  binary_relocation: False
  noarch: generic

requirements:
  build:
    - cmake
    - android-ndk

about:
  home: https://libjpeg-turbo.org/
  summary: libjpeg-turbo is a JPEG image codec that uses SIMD instructions
  license: BSD
