{% set version = "5.2.4" %}

package:
  name: android-liblzma
  version: '{{ version }}'

source:
  # sourceforge is ....
  git_url: https://git.tukaani.org/xz.git
  git_tag: v{{ version }}

build:
  number: 1
  binary_relocation: False
  noarch: generic

#requirements:
#  build:
#  #  - autopoint

about:
  home: http://github.com/codelv/enaml-native
  license: GPLv3
