{% set name = "atom" %}
{% set version = "0.9.1" %}
{% set hash_type = "sha256" %}
{% set hash_value = "025cdd2606ea9cf3b4c3a10f3267ae98652bc7acdb528aa1cf4b2df3ba4f5d6a" %}
package:
  name: android-{{ name|lower }}
  version: '{{ version }}'

source:
  #git_url: https://github.com/nucleic/atom.git
  #git_rev: main
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'


requirements:
  build:
    - python
    - cppy
    - pip-cppy
    - android-ndk
    - android-libcxx
    - android-python * py311*
  run:
    - python
    - android-libcxx
    - android-python * py311*

build:
  binary_relocation: False
  string: 'py311'
  noarch: generic

about:
  home: https://github.com/nucleic/atom
  summary: Memory efficient Python objects
  license: BSD
