{% set name = "atom" %}
{% set version = "0.7.0" %}
{% set hash_type = "sha256" %}
{% set hash_value = "4055fbdeeb692d3d52c6e3c628d7513fc71f147920cac7d0da05b6dbb5ec8c8d" %}
package:
  name: android-{{ name|lower }}
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

requirements:
  build:
    - python
    - cppy
    - pip-cppy
    - android-ndk
    - android-python * py{{CONDA_PY}}*
  run:
    - python
    - android-python * py{{CONDA_PY}}*

build:
  binary_relocation: False
  noarch: generic

about:
  home: https://github.com/nucleic/atom
  summary: Memory efficient Python objects
  license: BSD
