package:
  name: android-libcxx
  version: '14'

build:
  number: 1
  binary_relocation: False
  noarch: generic

requirements:
  build:
    - android-ndk

about:
  summary: libc++_shared from the Android NDK
  license:  MIT
