{% set version = "4.4.33" %}

package:
  name: android-libxcrypt
  version: '{{ version }}'

source:
  url: https://github.com/besser82/libxcrypt/releases/download/v{{ version }}/libxcrypt-{{ version }}.tar.xz
  sha256: e87acf9c652c573a4713d5582159f98f305d56ed5f754ce64f57d4194d6b3a6f

build:
  number: 1
  binary_relocation: False
  noarch: generic

requirements:
  build:
    - android-ndk
about:
  home: https://github.com/besser82/libxcrypt
  summary: Extended crypt library for descrypt, md5crypt, bcrypt, and others
  license: LGPL
