context:
  version: 4.4.28

package:
  name: android-libxcrypt
  version: '{{ version }}'

source:
  url: https://github.com/besser82/libxcrypt/releases/download/v{{ version }}/libxcrypt-{{ version }}.tar.xz
  sha256: 9e936811f9fad11dbca33ca19bd97c55c52eb3ca15901f27ade046cc79e69e87

build:
  number: 1
  binary_relocation: false
  noarch: generic

requirements:
  build:
    - android-ndk
about:
  home: https://github.com/besser82/libxcrypt
  summary: Extended crypt library for descrypt, md5crypt, bcrypt, and others
  license: LGPL

