{% set version = "3.7.4" %}
{% set md5 = "d33e4aae66097051c2eca45ee3604803" %}
package:
  name: android-python
  version: {{version}}
source:
  url:  https://www.python.org/ftp/python/{{version}}/Python-{{version}}.tar.xz
  md5: {{md5}}

requirements:
  build:
    - python>=3.7
    - android-libffi
    - android-openssl
    - android-sqlite
    - android-liblzma
    - android-libbz2
  run:
    - python>=3.7
build:
  number: 1
  binary_relocation: False
  noarch: generic

about:
  home: http://github.com/codelv/enaml-native
  license: GPLv3
