
package:
  name: android-lz4
  version: 1.8.1.2

source:
  url: https://github.com/lz4/lz4/archive/v1.8.1.2.tar.gz
  sha1: d16dd5062b98a715d18e2b0f7d8e1a595272b8d6
  patches:
    - makefile.patch

build:
  number: 1
  binary_relocation: False
  noarch: generic

about:
  home: http://github.com/codelv/enaml-native
  license: GPLv3