context:
  version: 1.9.3
  sha256: 030644df4611007ff7dc962d981f390361e6c97a34e5cbc393ddfbe019ffe2c1

package:
  name: android-lz4
  version: '{{ version }}'

source:
  url: https://github.com/lz4/lz4/archive/refs/tags/v{{version}}.tar.gz
  sha256: '{{ sha256 }}'

requirements:
  build:
    - android-ndk

build:
  number: 1
  binary_relocation: false
  noarch: generic

about:
  home: http://github.com/codelv/enaml-native
  license: GPLv3

