{% set name = "pytz" %}
{% set version = "2023.3" %}
package:
  name: pip-{{ name|lower }}
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1d8ce29db189191fb55338ee6d0387d82ab59f3d00eac103412d64e0ebd0c588

build:
  number: 0
  noarch: true
  script:
  - export CC=/bin/false
  - export CXX=/bin/false
  - 'python -m pip install . -vv --no-compile --target=$PREFIX/android/arm/python/site-packages '
  - 'python -m pip install . -vv --no-compile --target=$PREFIX/android/arm64/python/site-packages '
  - 'python -m pip install . -vv --no-compile --target=$PREFIX/android/x86/python/site-packages '
  - 'python -m pip install . -vv --no-compile --target=$PREFIX/android/x86_64/python/site-packages '
  - 'python -m pip install . -vv --no-compile --target=$PREFIX/iphoneos/python/site-packages '
  - 'python -m pip install . -vv --no-compile --target=$PREFIX/iphonesimulator/python/site-packages '

requirements: {}
about:
  home: The package home page
  license: MIT
  license_family: MIT
  license_file:
  summary: World timezone definitions, modern and historical Built for Android and iOS apps using enaml-native.
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
  - your-github-id-here
