context: {}
package:

  name: android-graphviz
  version: 2.40.1

source:
  # sourceforge is ....
  url: https://graphviz.gitlab.io/pub/graphviz/stable/SOURCES/graphviz.tar.gz
  md5: 4ea6fd64603536406166600bcc296fc8
  patches:
    #- stdint.patch
    - build.patch

build:
  number: 1
  binary_relocation: false
  noarch: generic

requirements:
  build:
    - bison
    - flex

about:
  home: https://graphviz.org/
  summary: Graphviz - Graph Visualization Tools
  license: EPL

