package:
  name: ios-python
  version: 2.7.14

source:
  url:  https://www.python.org/ftp/python/2.7.14/Python-2.7.14.tar.xz
  md5: 1f6db41ad91d9eb0a6f0c769b8613c5b

build:
  number: 0

outputs:
  - name: iphoneos-python2.7
    files:
      - iphoneos/libpython2.7.dylib
      - iphoneos/python2.7/*
      - iphoneos/include/Python/*.h

  - name: iphonesimulator-python2.7
    files:
      - iphonesimulator/libpython2.7.dylib
      - iphonesimulator/python2.7/*
      - iphonesimulator/include/Python/*.h

about:
  home: http://github.com/codelv/enaml-native
  license: MIT