sdk:
  - iphonesimulator
  - iphonesimulator
  - iphoneos
  - iphoneos

arch:
  - i386
  - x86_64
  - armv7
  - arm64

triple:
  - i386-apple-darwin11
  - x86_64-apple-darwin13
  - arm-apple-darwin11
  - aarch64-apple-darwin13

zip_keys:
  - sdk
  - arch
  - triple