{% set name = "pyzmq" %}
{% set version = "22.3.0" %}
{% set hash_type = "sha256" %}
{% set hash_value = "8eddc033e716f8c91c6a2112f0a8ebc5e00532b4a6ae1eb0ccc48e027f9c671c" %}
package:
  name: android-{{ name|lower }}
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

requirements:
  build:
    - python
    - cython
    - android-ndk
    - android-libzmq
    - android-libsodium
    - android-python * py{{CONDA_PY}}*
  run:
    - python
    - android-libzmq
    - android-libffi
    - android-python * py{{CONDA_PY}}*

build:
  number: 0
  binary_relocation: False
  noarch: generic

about:
  home: https://pyzmq.readthedocs.io/en/latest/
  summary:  PyZMQ is the Python bindings for ØMQ. Built for Android apps using enaml-native.
  license:  BSD
