{% set version = "7.1.0" %}
package:
  name: android-harfbuzz
  version: {{version}}

source:
  url: https://github.com/harfbuzz/harfbuzz/releases/download/{{version}}/harfbuzz-{{version}}.tar.xz
  sha256: f135a61cd464c9ed6bc9823764c188f276c3850a8dc904628de2a87966b7077b

requirements:
  build:
    - android-ndk

build:
  number: 1
  binary_relocation: False
  noarch: generic

about:
  home: http://harfbuzz.org/
  summary:  HarfBuzz OpenType text shaping engine
  license:  MIT
