{% set name = "kiwisolver" %}
{% set version = "1.4.4" %}
{% set hash_type = "sha256" %}
{% set hash_value = "d41997519fcba4a1e46eb4a2fe31bc12f0ff957b2b81bac28db24744f333e955" %}
package:
  name: android-{{ name|lower }}
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

requirements:
  build:
    - python
    - cppy
    - pip-cppy
    - android-ndk
    - android-libcxx
    - android-python * py311*
  run:
    - python
    - android-libcxx
    - android-python * py311*

build:
  binary_relocation: False
  noarch: generic
  string: 'py311'

about:
  home: https://github.com/nucleic/atom
  summary: Memory efficient Python objects
  license: BSD
