{% set name = "pandas" %}
{% set version = "1.4.1" %}
{% set hash_type = "sha256" %}
{% set hash_value = "8db93ec98ac7cb5f8ac1420c10f5e3c43533153f253fe7fb6d891cf5aa2b80d2" %}
package:
  name: android-{{ name|lower }}
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

requirements:
  build:
    - python
    - cython
    - pytz
    - tempita
    - numpy 1.22
    - python-dateutil
    - android-ndk
    - android-numpy * py310*
    - android-python * py310*
  run:
    - python
    - android-numpy * py310*
    - android-python * py310*
    - pip-pytz
    - pip-python-dateutil

build:
  number: 0
  binary_relocation: False
  noarch: generic
  string: 'py310'

about:
  home: https://pandas.pydata.org/
  summary:  "pandas is an open source, BSD-licensed library providing high-performance, easy-to-use data structures and data analysis tools for the Python programming language"
  license:  BSD
