context:
  name: pandas
  version: 0.22.0
  hash_type: sha256
  hash_value: 44a94091dd71f05922eec661638ec1a35f26d573c119aa2fad964f10a2880e6c

package:
  name: android-{{ name|lower }}
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

requirements:
  build:
    - python
    - cython
    - pytz
    - tempita
    - numpy
    - python-dateutil
    - android-numpy
    - android-python * py{{CONDA_PY}}*
  run:
    - python
    - android-numpy
    - android-python * py{{CONDA_PY}}*
    - pip-pytz
    - pip-python-dateutil

build:
  number: 0
  binary_relocation: false
  noarch: generic

about:
  home: https://pandas.pydata.org/
  summary: pandas is an open source, BSD-licensed library providing high-performance, easy-to-use data structures and data analysis tools for the Python programming language
  license: BSD

