package:
  name: android-sqlite
  version: 3.22.0

source:
  url: https://www.sqlite.org/2018/sqlite-autoconf-3220000.tar.gz
  sha1: 2fb24ec12001926d5209d2da90d252b9825366ac

build:
  number: 1
  binary_relocation: False

about:
  home: http://github.com/codelv/enaml-native
  license: GPLv3