package:
  name: android-sqlite
  version: 3.28.0

source:
  url: https://www.sqlite.org/2019/sqlite-autoconf-3280000.tar.gz
  sha1: 01b9d8fc77085e144dddc87456c9783e53d09a53

build:
  number: 1
  binary_relocation: False
  noarch: generic

about:
  home: http://github.com/codelv/enaml-native
  license: GPLv3
