package:
  name: android-sqlite
  version: 3.41.2

source:
  url: https://sqlite.org/2023/sqlite-autoconf-3410200.tar.gz
  sha256: e98c100dd1da4e30fa460761dab7c0b91a50b785e167f8c57acc46514fae9499

requirements:
  build:
    - android-ndk

build:
  number: 1
  binary_relocation: False
  noarch: generic

about:
  home: http://github.com/codelv/enaml-native
  license: GPLv3
