package:
  name: android-sqlite
  version: 3.29.0

source:
  url: https://sqlite.org/2019/sqlite-autoconf-3290000.tar.gz
  sha1: 053d8237eb9741b0e297073810668c2611a8e38e

build:
  number: 1
  binary_relocation: False
  noarch: generic

about:
  home: http://github.com/codelv/enaml-native
  license: GPLv3
