package:
  name: android-pyproj
  version: 1.9.5.1

source:
  url: https://github.com/jswhit/pyproj/archive/v1.9.5.1rel.tar.gz
  sha1: 6f70f7f1c4d618bf0109cb29f3d0caecb18825a3

requirements:
  build:
    - python
    - cython
    - numpy 1.22
    - android-ndk
    - android-python * py311*

  run:
    - python
    - android-python * py311*

build:
  number: 0
  binary_relocation: False
  noarch: generic
  string: 'py311'

about:
  home: http://github.com/codelv/enaml-native
  license: GPLv3
