{% set version = "2.10.3" %}

package:
  name: android-libxml2
  version: '{{ version }}'

source:
  url: https://github.com/GNOME/libxml2/archive/refs/tags/v{{version}}.tar.gz
  sha256: 3f9fb74bb02049f3454892c88d3e57a23e30a88a7d444a80064625af2f543898

build:
  number: 1
  binary_relocation: False
  noarch: generic

requirements:
  build:
    - android-liblzma
    - android-ndk
  run:
    - android-liblzma
about:
  home: http://www.xmlsoft.org/
  summary:  The XML C parser and toolkit of Gnome. Built for Android apps using enaml-native.
  license:  MIT
