{% set version = "2.9.9" %}

package:
  name: android-libxml2
  version: '{{ version }}'

source:
  url: https://github.com/GNOME/libxml2/archive/v{{ version }}.tar.gz
  sha256: d673f0284cec867ee00872a8152e0c3c09852f17fd9aa93f07579a37534f0bfe

build:
  number: 1
  binary_relocation: False
  noarch: generic

requirements:
  build:
    - android-liblzma
  run:
    - android-liblzma
about:
  home: http://www.xmlsoft.org/
  summary:  The XML C parser and toolkit of Gnome. Built for Android apps using enaml-native.
  license:  MIT
