{% set name = "futures" %}
{% set version = "3.2.0" %}
{% set hash_type = "sha256" %}
{% set hash_value = "9ec02aa7d674acb8618afb127e27fde7fc68994c0437ad759fa094a574adb265" %}
package:
  name: pip-{{ name|lower }}
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script_env:
  - CC
  - CXX
  noarch: true
  script: 

  - python setup.py install  --single-version-externally-managed --record=record.txt --no-compile --install-base=$PREFIX/android/arm --install-lib=$PREFIX/android/arm/python/site-packages --install-scripts=$PREFIX/android/arm/scripts --install-data=$PREFIX/android/arm/data --install-headers=$PREFIX/android/arm/include
  - python setup.py install  --single-version-externally-managed --record=record.txt --no-compile --install-base=$PREFIX/android/arm64 --install-lib=$PREFIX/android/arm64/python/site-packages --install-scripts=$PREFIX/android/arm64/scripts --install-data=$PREFIX/android/arm64/data --install-headers=$PREFIX/android/arm64/include
  - python setup.py install  --single-version-externally-managed --record=record.txt --no-compile --install-base=$PREFIX/android/x86 --install-lib=$PREFIX/android/x86/python/site-packages --install-scripts=$PREFIX/android/x86/scripts --install-data=$PREFIX/android/x86/data --install-headers=$PREFIX/android/x86/include
  - python setup.py install  --single-version-externally-managed --record=record.txt --no-compile --install-base=$PREFIX/android/x86_64 --install-lib=$PREFIX/android/x86_64/python/site-packages --install-scripts=$PREFIX/android/x86_64/scripts --install-data=$PREFIX/android/x86_64/data --install-headers=$PREFIX/android/x86_64/include
  - python setup.py install  --single-version-externally-managed --record=record.txt --no-compile --install-base=$PREFIX/iphoneos --install-lib=$PREFIX/iphoneos/python/site-packages --install-scripts=$PREFIX/iphoneos/scripts --install-data=$PREFIX/iphoneos/data --install-headers=$PREFIX/iphoneos/include
  - python setup.py install  --single-version-externally-managed --record=record.txt --no-compile --install-base=$PREFIX/iphonesimulator --install-lib=$PREFIX/iphonesimulator/python/site-packages --install-scripts=$PREFIX/iphonesimulator/scripts --install-data=$PREFIX/iphonesimulator/data --install-headers=$PREFIX/iphonesimulator/include
requirements: {}
about:
  home: https://github.com/agronholm/pythonfutures
  license: Python Software Foundation License
  license_family: OTHER
  license_file: ''
  summary: Backport of the concurrent.futures package from Python 3
  description: ".. image:: https://travis-ci.org/agronholm/pythonfutures.svg?branch=master\n  :target: https://travis-ci.org/agronholm/pythonfutures\n  :alt: Build Status\n\nThis is a backport of the `concurrent.futures`_ standard library module to Python 2.\n\nIt should not be installed on Python 3, although there should be no harm in doing so, as the\nstandard library takes precedence over third party libraries.\n\nTo conditionally require this library only on Python 2, you can do this in your ``setup.py``:\n\n.. code-block:: python\n\n    setup(\n        ...\n        extras_require={\n            ':python_version == \"2.7\"': ['futures']\n        }\n    )\n\nOr, using the newer syntax:\n\n.. code-block:: python\n\n    setup(\n        ...\n        install_requires={\n            'futures; python_version == \"2.7\"'\n        }\n    )\n\n.. warning:: The ``ProcessPoolExecutor`` class has known (unfixable) problems on Python 2 and\n  should not be relied on for mission critical work.\n\n\
    .. _concurrent.futures: https://docs.python.org/library/concurrent.futures.html\n\n\n"
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
