{% set version = "3.10.2" %}
{% set md5 = "14e8c22458ed7779a1957b26cde01db9" %}
package:
  name: android-python
  version: {{version}}
source:
  url:  https://www.python.org/ftp/python/{{version}}/Python-{{version}}.tar.xz
  md5: {{md5}}

requirements:
  build:
    - python
    - android-ndk
    - android-libffi
    - android-openssl
    - android-sqlite
    - android-liblzma
    - android-libbz2
    - android-libuuid
    - android-libxcrypt
  run:
    - python
build:
  number: 6
  string: 'py310'
  binary_relocation: False
  noarch: generic

about:
  home: http://github.com/codelv/enaml-native
  summary: Python for android.
  license: GPLv3
