{% set version = "3.11.3" %}
{% set md5 = "c8d52fc4fb8ad9932a11d86d142ee73a" %}
package:
  name: android-python
  version: {{version}}
source:
  url:  https://www.python.org/ftp/python/{{version}}/Python-{{version}}.tar.xz
  md5: {{md5}}

requirements:
  build:
    - python
    - android-ndk
    - android-libffi
    - android-openssl
    - android-sqlite
    - android-liblzma
    - android-libbz2
    - android-libuuid
    - android-libxcrypt
  run:
    - python
    - android-libxcrypt

build:
  number: 0
  string: 'py311'
  binary_relocation: False
  noarch: generic

about:
  home: http://github.com/codelv/enaml-native
  summary: Python for android.
  license: GPLv3
