{% set version = "2.7.16" %}
{% set md5 = "30157d85a2c0479c09ea2cbe61f2aaf5" %}
package:
  name: android-python
  version: {{version}}
source:
  url:  https://www.python.org/ftp/python/{{version}}/Python-{{version}}.tar.xz
  md5: {{md5}}
  patches:
      - patches/setup.patch
      - patches/sqlite.patch
      # For Kitcat 4.4
      #- patches/locale.patch

requirements:
  build:
    - python<3
    - android-libffi
    - android-openssl
    - android-sqlite
    - android-libbz2
  run:
    - python<3
build:
  number: 0
  binary_relocation: False
  noarch: generic
about:
  home: http://github.com/codelv/enaml-native
  license: GPLv3
