package:
  name: android-msgpack
  version: 0.5.6

source:
  url: https://github.com/msgpack/msgpack-python/archive/0.5.6.tar.gz
  md5: 6d644c06a87a5a111bbbf5b34b4be440

requirements:
  build:
    - python<=3
    - cython
    - android-python
  run:
    - android-python

build:
  number: 0
  binary_relocation: False
  noarch: generic

about:
  home: http://github.com/codelv/enaml-native
  license: GPLv3