{% set version = "1.0.3" %}
package:
  name: android-msgpack
  version: {{ version }}

source:
  url: https://github.com/msgpack/msgpack-python/archive/refs/tags/v{{version}}.tar.gz
  sha256: 576a1835a8b48d5861c883a6e10fd374065c6ae56287b221d1a4791e9529c71c

requirements:
  build:
    - python
    - cython
    - android-ndk
    - android-libxcrypt
    - android-python * py310*
  run:
    - python
    - android-python * py310*

build:
  number: 1
  binary_relocation: False
  noarch: generic
  string: 'py310'

about:
  home: http://github.com/codelv/enaml-native
  license: GPLv3
