package:
  name: android-msgpack
  version: 0.5.6

source:
  url: https://github.com/msgpack/msgpack-python/archive/0.5.6.tar.gz
  md5: e05e0edfebdd32d11b02bea88381595e

requirements:
  build:
    - python
    - cython
    - android-python * py{{CONDA_PY}}*
  run:
    - python
    - android-python * py{{CONDA_PY}}*

build:
  number: 0
  binary_relocation: False
  noarch: generic

about:
  home: http://github.com/codelv/enaml-native
  license: GPLv3