{% set version = "1.0.5" %}
package:
  name: android-msgpack
  version: {{ version }}

source:
  url: https://github.com/msgpack/msgpack-python/archive/refs/tags/v{{version}}.tar.gz
  sha256: 34287cb609f0966c0d48f6e22e956b7485942169d820d0e3f4834573d425ef9b

requirements:
  build:
    - python
    - cython
    - android-ndk
    - android-libxcrypt
    - android-python * py311*
  run:
    - python
    - android-python * py311*

build:
  number: 1
  binary_relocation: False
  noarch: generic
  string: 'py311'

about:
  home: http://github.com/codelv/enaml-native
  license: GPLv3
