{% set name = "cffi" %}
{% set version = "1.15.1" %}
{% set hash_type = "sha256" %}
{% set hash_value = "d400bfb9a37b1351253cb402671cea7e89bdecc294e8016a707f6d1d8ac934f9" %}
package:
  name: android-{{ name|lower }}
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

requirements:
  build:
    - python
    - android-ndk
    - android-python * py311*
    - android-libffi
  run:
    - python
    - android-python * py311*
    - android-libffi

build:
  number: 0
  binary_relocation: False
  string: 'py311'
  noarch: generic

about:
  home: http://cffi.readthedocs.org/
  summary: Foreign Function Interface for Python calling C code. Built for Android apps using enaml-native.
  license:  MIT
