context:
  name: cffi
  version: 1.15.0
  hash_type: sha256
  hash_value: 920f0d66a896c2d99f0adbb391f990a84091179542c205fa53ce5787aff87954

package:
  name: android-{{ name|lower }}
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

requirements:
  build:
    - python
    - android-ndk
    - android-python * py{{CONDA_PY}}*
    - android-libffi
  run:
    - python
    - android-python * py{{CONDA_PY}}*
    - android-libffi

build:
  number: 0
  binary_relocation: false
  noarch: generic

about:
  home: http://cffi.readthedocs.org/
  summary: Foreign Function Interface for Python calling C code. Built for Android apps using enaml-native.
  license: MIT

