package:
  name: android-opencv
  version: 4.5.5

source:
  url: https://github.com/opencv/opencv/archive/4.0.0.tar.gz
  sha256: a1cfdcf6619387ca9e232687504da996aaa9f7b5689986b8331ec02cb61d28ad

requirements:
  build:
    - cmake
    - libwebp
    - android-ndk

channels:
   - rustychris


build:
  number: 1
  binary_relocation: False
  noarch: generic

about:
  home: https://opencv.org/
  summary: "OPENCV: Open Source Computer Vision Library"
  license: BSD
