context: {}
package:

  name: android-opencv
  version: 4.0.0

source:
  url: https://github.com/opencv/opencv/archive/4.0.0.tar.gz
  sha256: 3787b3cc7b21bba1441819cb00c636911a846c0392ddf6211d398040a1e4886c

requirements:
  build:
    - cmake
    - libwebp


channels:
  - rustychris


build:
  number: 1
  binary_relocation: false
  noarch: generic

about:
  home: https://opencv.org/
  summary: 'OPENCV: Open Source Computer Vision Library'
  license: BSD

