context:
  version: '4.5.5'
package:

  name: android-opencv
  version: '{{version}}'

source:
  url: 'https://github.com/opencv/opencv/archive/refs/tags/{{version}}.tar.gz'
  sha256: a1cfdcf6619387ca9e232687504da996aaa9f7b5689986b8331ec02cb61d28ad

requirements:
  build:
    - cmake
    - libwebp
    - android-ndk


channels:
  - rustychris


build:
  number: 1
  binary_relocation: false
  noarch: generic

about:
  home: https://opencv.org/
  summary: 'OPENCV: Open Source Computer Vision Library'
  license: BSD

