{% set version = "1.0.9" %}

package:
  name: android-brotli
  version: '{{ version }}'

source:
  url: https://github.com/google/brotli/archive/refs/tags/v{{version}}.tar.gz
  sha256: f9e8d81d0405ba66d181529af42a3354f838c939095ff99930da6aa9cdf6fe46

build:
  number: 0
  binary_relocation: False
  noarch: generic

requirements:
  build:
    - android-ndk
    - cmake

about:
  home: http://github.com/codelv/enaml-native
  summary:  Brotli compression format
  license: public domain

