{% set version = "1.1.1t" %}
{% set sha256 = "8dee9b24bdb1dcbf0c3d1e9b02fb8f6bf22165e807f45adeb7c9677536859d3b" %}
package:
  name: android-openssl
  version: {{version}}

source:
  url: https://www.openssl.org/source/openssl-{{version}}.tar.gz
  sha256: {{sha256}}

requirements:
  build:
    - android-ndk

build:
  number: 1
  binary_relocation: False
  noarch: generic

about:
  home: http://github.com/codelv/enaml-native
  license: GPLv3
