
package:
  name: android-openssl
  version: 1.0.2o

source:
  url: https://www.openssl.org/source/openssl-1.0.2o.tar.gz
  sha256: ec3f5c9714ba0fd45cb4e087301eb1336c317e0d20b575a125050470e8089e4d

build:
  number: 1
  binary_relocation: False
  noarch: generic

about:
  home: http://github.com/codelv/enaml-native
  license: GPLv3