
package:
  name: android-openssl
  version: 1.1.0k

source:
  url: https://www.openssl.org/source/openssl-1.1.0k.tar.gz
  sha256: efa4965f4f773574d6cbda1cf874dbbe455ab1c0d4f906115f867d30444470b1

build:
  number: 1
  binary_relocation: False
  noarch: generic

about:
  home: http://github.com/codelv/enaml-native
  license: GPLv3
