{% set version = "1.1.1m" %}
{% set sha256 = "f89199be8b23ca45fc7cb9f1d8d3ee67312318286ad030f5316aca6462db6c96" %}
package:
  name: android-openssl
  version: 1.1.1i

source:
  url: https://www.openssl.org/source/openssl-{{version}}.tar.gz
  sha256: {{sha256}}

requirements:
  build:
    - android-ndk

build:
  number: 1
  binary_relocation: False
  noarch: generic

about:
  home: http://github.com/codelv/enaml-native
  license: GPLv3
