package:
  name: ios-enaml
  version: 0.10.3.a0

source:
  url: https://github.com/nucleic/enaml/archive/0.10.3.a0.tar.gz
  #md5: 04525c2c83104a6f2be3b5c928dd9d25

requirements:
  build:
    - ios-python
  run:
    - ios-python
    - ios-atom>=0.4.2.a0
    - pip-ply==3.11

build:
  number: 0
  binary_relocation: False

about:
  home: http://github.com/codelv/enaml-native
  license: GPLv3