context:
  version: 1.0.3

package:
  name: android-libuuid
  version: '{{version}}'

source:
  # Seems to be hosted on sorceforge but sorceforge is spammy...
  url: https://iweb.dl.sourceforge.net/project/libuuid/libuuid-1.0.3.tar.gz
  sha256: 46af3275291091009ad7f1b899de3d0cea0252737550e7919d17237997db5644

requirements:
  build:
    - android-ndk

build:
  number: 1
  binary_relocation: false
  noarch: generic

about:
  home: https://sourceforge.net/projects/libuuid/
  summary: Portable uuid C library
  license: BSD

