package:
  name: android-ndk-libs
  version: 26

build:
  number: 0
  binary_relocation: False
  noarch: generic

about:
  summary: Libs from the Android NDK version. This should only be used for building NOT running!!!!
  license:  MIT
