package:
  name: android-shapely
  version: 1.6.4

source:
  url: https://github.com/Toblerity/Shapely/archive/1.6.4.tar.gz
  sha1: 9de76f6b1d450ff1ca0df30ac3aac5bf903d94e5
  patches:
    - setup.patch

requirements:
  build:
    - python
    - cython
    - numpy
    - android-ndk
    - android-python * py310*
    - android-libgeos

  run:
    - python
    - android-python * py310*
    - android-libgeos

build:
  number: 0
  binary_relocation: False
  noarch: generic
  string: 'py310'

about:
  home: http://github.com/codelv/enaml-native
  license: GPLv3
