
package:
  name: ios-openssl
  version: 1.0.2n

source:
  url: https://www.openssl.org/source/openssl-1.0.2n.tar.gz
  sha256: 370babb75f278c39e0c50e8c4e7493bc0f18db6867478341a832a982fd15a8fe

build:
  number: 1
  binary_relocation: False

outputs:
  - name: iphoneos-openssl
    files:
      - iphoneos/lib/libssl.dylib
      - iphoneos/lib/libcrypto.dylib
      - iphoneos/include/openssl/*.h

  - name: iphonesimulator-openssl
    files:
      - iphonesimulator/lib/libssl.dylib
      - iphonesimulator/lib/libcrypto.dylib
      - iphonesimulator/include/openssl/*.h
about:
  home: http://github.com/codelv/enaml-native
  license: MIT