package:
  name: android-numpy
  version: 1.14.2

source:
  url: https://github.com/numpy/numpy/archive/v1.14.2.tar.gz
  patches:
    - numpy.patch

requirements:
  build:
    - python<3
    - cython
    - android-python
  run:
    - android-python

build:
  number: 0
  binary_relocation: False
  noarch: generic

about:
  home: http://github.com/codelv/enaml-native
  license: GPLv3