
package:
  name: android-numpy
  version: 1.14.3

source:
  url: https://github.com/numpy/numpy/releases/download/v1.14.3/numpy-1.14.3.tar.gz
  sha256: cfcfc7a9a8ba4275c60a815c683d59ac5e7aa9362d76573b6cc4324ffb1235fa

requirements:
  build:
    - python
    - cython
    - android-python * py{{CONDA_PY}}*
  run:
    - python
    - android-python * py{{CONDA_PY}}*

build:
  number: 0
  binary_relocation: False
  noarch: generic

about:
  home: http://github.com/codelv/enaml-native
  license: GPLv3