{% set version = "2.9.1" %}
package:
  name: android-freetype
  version: {{version}}

source:
  url: https://download.savannah.gnu.org/releases/freetype/freetype-{{version}}.tar.bz2
  sha256: db8d87ea720ea9d5edc5388fc7a0497bb11ba9fe972245e0f7f4c7e8b1e1e84d

requirements:
  build:
    - android-libpng
    - android-harfbuzz
  run:
    - android-libpng
    - android-harfbuzz

build:
  number: 1
  binary_relocation: False
  noarch: generic

about:
  home: https://www.freetype.org/index.html
  summary:  FreeType is a freely available software library to render fonts.
  license:  FTL