{% set version = "2.13.0" %}
package:
  name: android-freetype
  version: {{version}}

source:
  #url: https://download.savannah.gnu.org/releases/freetype/freetype-{{version}}.tar.xz
  url: https://downloads.sourceforge.net/project/freetype/freetype2/{{version}}/freetype-{{version}}.tar.gz
  sha256: a7aca0e532a276ea8d85bd31149f0a74c33d19c8d287116ef8f5f8357b4f1f80

requirements:
  build:
    - android-libpng
    - android-harfbuzz
    - android-ndk
  run:
    - android-libpng
    - android-harfbuzz

build:
  number: 0
  binary_relocation: False
  noarch: generic

about:
  home: https://www.freetype.org/index.html
  summary:  FreeType is a freely available software library to render fonts.
  license:  FTL
