{% set version = "1.1.33" %}

package:
  name: android-libxslt
  version: '{{ version }}'

source:
  url: https://github.com/GNOME/libxslt/archive/v{{ version }}.tar.gz
  sha256: cb4bca0adbabf218948550bdf1f1b20120e7ae8322c7d599be4b58908946aad8

build:
  number: 1
  binary_relocation: False
  noarch: generic

requirements:
  build:
    - android-libxml2
    #- android-ndk-libs
  run:
    - android-libxml2
about:
  home: https://github.com/GNOME/libxslt
  summary:  an implementation of XSLT 1.0 and common extensions like EXSLT for libxml2. Built for Android apps using enaml-native.
  license:  MIT
