{% set version = "3.4.4" %}
package:
  name: android-libffi
  version: {{version}}

source:
  url: https://github.com/libffi/libffi/releases/download/v{{version}}/libffi-{{version}}.tar.gz
  sha256: d66c56ad259a82cf2a9dfc408b32bf5da52371500b84745f7fb8b645712df676

requirements:
  build:
    - android-ndk

build:
  number: 0
  binary_relocation: False
  noarch: generic

about:
  home: https://sourceware.org/libffi/
  summary: A portable foreign-function interface library.
  license: MIT
