
package:
  name: android-libffi
  version: 3.3.rc0

source:
  url: https://github.com/libffi/libffi/archive/v3.3-rc0.tar.gz
  sha256: db41cfb9ec8052fcd116a94c12237303c4447af4844d50e4fea7163661e31743

build:
  number: 1
  binary_relocation: False
  noarch: generic

about:
  home: http://github.com/codelv/enaml-native
  license: GPLv3
