package:
  name: ios-libffi
  version: 3.2.1

source:
  url: https://github.com/libffi/libffi/archive/v3.2.1.tar.gz

build:
  number: 1
  binary_relocation: False

outputs:
  - name: iphoneos-libffi
    files:
      - iphoneos/lib/libffi.dylib
      - iphoneos/lib/libffi.dylib.dSYM
      - iphoneos/include/*
  - name: iphonesimulator-libffi
    files:
      - iphonesimulator/lib/libffi.dylib
      - iphonesimulator/lib/libffi.dylib.dSYM
      - iphonesimulator/include/*

about:
  home: http://github.com/codelv/enaml-native
  license: MIT