package:
  name: enaml-native
  version: 4.0.0.a3

source:
  url: https://github.com/codelv/enaml-native/archive/v4.0.0.a3.tar.gz
  #sha1: 180fb4ba46a8c7483933e802ac23d99748273bac

requirements:
  build:
    - python

  run:
    - python
    - android-enaml
    - android-msgpack
    - ios-enaml # [osx]
    - ios-msgpack # [osx]

build:
  number: 1
  noarch: generic

about:
  home: http://github.com/codelv/enaml-native
  license: GPLv3