
package:
  name: android-libbz2
  version: 1.0.8

source:
  url: https://sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz
  sha256: ab5a03176ee106d3f0fa90e381da478ddae405918153cca248e682cd0c4a2269

build:
  number: 1
  binary_relocation: False
  noarch: generic

about:
  home: http://github.com/codelv/enaml-native
  license: GPLv3
