{% set version = "1.0.16" %}
package:
  name: android-libsodium
  version: {{version}}

source:
  url: https://github.com/jedisct1/libsodium/releases/download/{{version}}/libsodium-{{version}}.tar.gz

build:
  number: 1
  binary_relocation: False
  noarch: generic

about:
  home: https://github.com/jedisct1/libsodium
  summary:  Sodium is a new, easy-to-use software library for encryption, decryption, signatures, password hashing and more.
  license:  ISC