jobs:
  android-ndk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install micromamba
      run: |
        mkdir ~/micromamba
        cd ~/micromamba
        wget -qO- https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
        echo "$HOME/micromamba/bin:$PATH" >> $GITHUB_PATH
    - name: Setup micromamba
      run: |
        micromamba install -c conda-forge python=3.10 boa
    - name: Install system deps
      run: sudo apt-get install -y autopoint texinfo rename
    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - id: android-cache
      name: Cache Android NDK
      uses: actions/cache@v2
      with:
        key: linux-android-ndk-23.1.7779620
        path: ~/Android
    - if: steps.android-cache.outputs.cache-hit != 'true'
      name: Setup android NDK
      run: |
        export ANDROID_HOME="$HOME/Android/Sdk"
        export ANDROID_SDK_ROOT="$HOME/Android/Sdk"
        export PATH="$PATH:$ANDROID_HOME/cmdline-tools/latest/bin"
        mkdir -p $ANDROID_HOME
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip
        unzip -e commandlinetools-linux-8092744_latest.zip -d $ANDROID_HOME/cmdline-tools
        mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
        yes | sdkmanager --licenses > /dev/null
        sdkmanager --install tools
        sdkmanager --install platform-tools
        sdkmanager --install "ndk;23.1.7779620"
    - name: Build recipe
      run: boa build android-ndk --target-platform=linux-64
    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: android-ndk-3.10
        path: ~/bin/micromamba/conda-bld/*/android-ndk*.bz2
name: CI
'on': push
