name: CI
on: [push]
jobs:
  android-python:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v2
      - name: Setup python ${{ matrix.python-version}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup Android NDK
        uses: android-actions/setup-android@v2
      - name: Install conda build
        run: conda install conda-build
      - name: Build recipe
        run: conda build --py=${{matrix.python-version}} android-python
