name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package-name: [
            'android-ndk',
            'android-libcxx',
            'android-liblzma',
            'android-sqlite',
            'android-libffi',
            'android-libsodium',
            'android-libuuid',
            'android-libpng',
            'android-libjpeg',
            'android-lz4',
            'android-freetype',
            'android-libxslt',
            'android-libxml2',
            'android-openssl',
            'android-harfbuzz',
            'android-python',
            'android-cffi',
            'android-atom',
            'android-msgpack',
            'android-kiwisolver',
            'android-enaml',
            'android-lxml',
            'pip-bytecode',
            'pip-cppy',
            'pip-tornado',
        ]
        python-version: ['3.10']
        ndk-version: ['23.1.7779620']
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Install system deps
        run: sudo apt-get install -y autopoint texinfo
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v2
        id: android-cache
        with:
          path: ~/Android
          key: ${{ runner.os }}-android-sdk-${{ matrix.ndk-version }}
      - name: Setup Android NDK
        if: steps.android-cache.outputs.cache-hit != 'true'
        run: |
            export ANDROID_HOME="$HOME/Android/Sdk"
            export ANDROID_SDK_ROOT="$HOME/Android/Sdk"
            export PATH="$PATH:$ANDROID_HOME/cmdline-tools/latest/bin"
            mkdir -p $ANDROID_HOME
            wget -q https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip
            unzip -q commandlinetools-linux-8092744_latest.zip -d $ANDROID_HOME/cmdline-tools
            mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
            yes | sdkmanager --licenses > /dev/null
            sdkmanager --install tools
            sdkmanager --install platform-tools
            sdkmanager --install "ndk;${{ matrix.ndk-version}}"
      - name: Install conda build
        run: conda install conda-build
      - uses: actions/cache@v2
        id: conda-bld-cache
        with:
          path: /usr/share/miniconda/conda-bld
          key: ${{ runner.os }}-conda-bld-cache-${{ matrix.pthon-version }}-${{ matrix.ndk-version }}
      - name: Build recipe
        run: conda build --py=${{matrix.python-version}} ${{matrix.package-name}}
